/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.GldClientes;
import bean.GldVendasRoupas;
import bean.GldUsuarios;
import bean.GldVendasRoupasProdutos;
import dao.ClientesDAO;
import dao.UsuariosDAO;
import dao.VendasDAO;
import dao.VendasProdutosDAO;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author u1845853
 */
public class JDlgVendas extends javax.swing.JDialog {
    
     ControllerVendasProdutos controllerVendasProd;
     private boolean incluir;
    
    
    private MaskFormatter mascaraDataVenda;
  private boolean pesquisado = false;
    /**
     * Creates new form JDlgPedidos
     */
    public JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Vendas");
         Util.habilitar(false, jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto,
            jTxtGldFormaPagamento, jCboGldClientes, jCboGldUsuarios, 
            jBtnGldConfirmar, jBtnGldCancelar, jBtnGldIncluirProd, jBtnGldAlterarProd, jBtnGldExcluirProd);
        
        
        
        ClientesDAO clientesDAO = new ClientesDAO();
        List lista = (List) clientesDAO.listAll();
        for (int i = 0; i < lista.size(); i++) {
            jCboGldClientes.addItem( (GldClientes) lista.get(i));            
        }
        
        UsuariosDAO usuariosDAO = new UsuariosDAO();
        List listaUsuarios = (List) usuariosDAO.listAll();
        for (int i = 0; i < listaUsuarios.size(); i++) {
         jCboGldUsuarios.addItem((GldUsuarios) listaUsuarios.get(i));            
}
        
         try {
          
            mascaraDataVenda = new MaskFormatter("##/##/####");
            jFmtGldDataVenda.setFormatterFactory(new DefaultFormatterFactory(mascaraDataVenda));
           
        } catch (ParseException ex) {
            Logger.getLogger(JDlgVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
         controllerVendasProd = new ControllerVendasProdutos();
        controllerVendasProd.setList(new ArrayList());
        jTable1.setModel(controllerVendasProd);
    }
     public void beanView(GldVendasRoupas vendasRoupas) {
        jTxtGldCodigo.setText(Util.IntTostr(vendasRoupas.getGldIdVendas() ));
        jFmtGldDataVenda.setText(Util.DataTostr(vendasRoupas.getGldDataVenda()));
        jTxtGldTotal.setText(Util.DoubleTostr(vendasRoupas.getGldTotal()));
        jTxtGldDesconto.setText(Util.DoubleTostr(vendasRoupas.getGldDesconto()));
        jTxtGldFormaPagamento.setText(vendasRoupas.getGldFormaPagamento());
        jCboGldClientes.setSelectedItem(vendasRoupas.getGldClientes());
        jCboGldUsuarios.setSelectedItem(vendasRoupas.getGldUsuarios());
        VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
        List lista = (List) vendasProdutosDAO.listProdutos(vendasRoupas);
        controllerVendasProd.setList(lista);
     }
    
    public GldVendasRoupas viewBean() {
        GldVendasRoupas gldVendasRoupas = new GldVendasRoupas();
        gldVendasRoupas.setGldIdVendas(Util.strToInt(jTxtGldCodigo.getText()));
        gldVendasRoupas.setGldDataVenda(Util.strToData(jFmtGldDataVenda.getText()));
        gldVendasRoupas.setGldTotal(Util.strToDouble(jTxtGldTotal.getText()));
        gldVendasRoupas.setGldDesconto(Util.strToDouble(jTxtGldDesconto.getText()));
        gldVendasRoupas.setGldFormaPagamento(jTxtGldFormaPagamento.getText());
        gldVendasRoupas.setGldClientes((GldClientes) jCboGldClientes.getSelectedItem());
        gldVendasRoupas.setGldUsuarios((GldUsuarios) jCboGldUsuarios.getSelectedItem());
        return gldVendasRoupas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtGldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFmtGldDataVenda = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jCboGldClientes = new javax.swing.JComboBox<GldClientes>();
        jCboGldUsuarios = new javax.swing.JComboBox<GldUsuarios>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtGldTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnGldCancelar = new javax.swing.JButton();
        jBtnGldPesquisar = new javax.swing.JButton();
        jBtnGldIncluir = new javax.swing.JButton();
        jBtnGldAlterar = new javax.swing.JButton();
        jBtnGldExcluir = new javax.swing.JButton();
        jBtnGldConfirmar = new javax.swing.JButton();
        jBtnGldIncluirProd = new javax.swing.JButton();
        jBtnGldAlterarProd = new javax.swing.JButton();
        jBtnGldExcluirProd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtGldDesconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtGldFormaPagamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("Data da venda");

        jLabel3.setText("Clientes");

        jCboGldUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboGldUsuariosActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuarios");

        jLabel5.setText("Valor total");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnGldCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnGldCancelar.setText("Cancelar");
        jBtnGldCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldCancelarActionPerformed(evt);
            }
        });

        jBtnGldPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnGldPesquisar.setText("Pesquisar");
        jBtnGldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldPesquisarActionPerformed(evt);
            }
        });

        jBtnGldIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnGldIncluir.setText("Incluir");
        jBtnGldIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldIncluirActionPerformed(evt);
            }
        });

        jBtnGldAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnGldAlterar.setText("Alterar");
        jBtnGldAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldAlterarActionPerformed(evt);
            }
        });

        jBtnGldExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnGldExcluir.setText("Excluir");
        jBtnGldExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldExcluirActionPerformed(evt);
            }
        });

        jBtnGldConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ok-25.png"))); // NOI18N
        jBtnGldConfirmar.setText("Confirmar");
        jBtnGldConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldConfirmarActionPerformed(evt);
            }
        });

        jBtnGldIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnGldIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldIncluirProdActionPerformed(evt);
            }
        });

        jBtnGldAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnGldAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldAlterarProdActionPerformed(evt);
            }
        });

        jBtnGldExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnGldExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGldExcluirProdActionPerformed(evt);
            }
        });

        jLabel7.setText("Desconto");

        jLabel8.setText("Forma de Pagamento");

        jTxtGldFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGldFormaPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnGldIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGldAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGldExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGldConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGldCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGldPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabel3)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel4)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnGldIncluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnGldAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnGldExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtGldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFmtGldDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCboGldClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCboGldUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtGldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtGldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtGldFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtGldDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboGldClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboGldUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGldFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnGldIncluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jBtnGldAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jBtnGldExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGldIncluir)
                    .addComponent(jBtnGldAlterar)
                    .addComponent(jBtnGldExcluir)
                    .addComponent(jBtnGldConfirmar)
                    .addComponent(jBtnGldCancelar)
                    .addComponent(jBtnGldPesquisar))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGldCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldCancelarActionPerformed
       
        Util.habilitar(false, jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto,
            jTxtGldFormaPagamento, jCboGldClientes, jCboGldUsuarios, 
            jBtnGldConfirmar, jBtnGldCancelar,jBtnGldIncluirProd, jBtnGldAlterarProd, jBtnGldExcluirProd);
        Util.habilitar(true, jBtnGldIncluir, jBtnGldAlterar, jBtnGldExcluir, jBtnGldPesquisar);
        Util.limpar(jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto);
        controllerVendasProd.setList(new ArrayList());
    }//GEN-LAST:event_jBtnGldCancelarActionPerformed

    private void jBtnGldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldPesquisarActionPerformed
        JDlgVendasPesquisar jDlgVendasPesquisar = new JDlgVendasPesquisar(null, true);
        jDlgVendasPesquisar.setTelaAnterior(this);
        jDlgVendasPesquisar.setVisible(true);
        pesquisado = true;
    }//GEN-LAST:event_jBtnGldPesquisarActionPerformed

    private void jBtnGldIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldIncluirActionPerformed
     
          Util.habilitar(true, jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto,
        jTxtGldFormaPagamento, jCboGldClientes, jCboGldUsuarios, 
        jBtnGldConfirmar, jBtnGldCancelar, jBtnGldIncluirProd, jBtnGldAlterarProd, jBtnGldExcluirProd);

       Util.habilitar(false, jBtnGldIncluir, jBtnGldAlterar, jBtnGldExcluir, jBtnGldPesquisar);

    Util.limpar(jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto, jTxtGldFormaPagamento);
        incluir = true;
    }//GEN-LAST:event_jBtnGldIncluirActionPerformed

    private void jBtnGldAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldAlterarActionPerformed
        if (!pesquisado) {
            JOptionPane.showMessageDialog(this, "É necessário pesquisar um usuário antes de alterar.");
            return;
        }
  Util.habilitar(true, jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto,
        jTxtGldFormaPagamento, jCboGldClientes, jCboGldUsuarios, 
        jBtnGldConfirmar, jBtnGldCancelar, jBtnGldIncluirProd, jBtnGldAlterarProd, jBtnGldExcluirProd);

       Util.habilitar(false, jBtnGldIncluir, jBtnGldAlterar, jBtnGldExcluir, jBtnGldPesquisar);

    jFmtGldDataVenda.grabFocus();
        incluir = false;
    }//GEN-LAST:event_jBtnGldAlterarActionPerformed

    private void jBtnGldExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldExcluirActionPerformed
     if (!pesquisado) {
            JOptionPane.showMessageDialog(this, "É necessário pesquisar um usuário antes de excluir.");
            return;
        }
        
         if (Util.pergunta("Deseja excluir ?") == true) {
            VendasDAO vendasDAO = new VendasDAO(); 
            VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
           
            
             for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                GldVendasRoupasProdutos gldVendasRoupasProdutos = controllerVendasProd.getBean(ind);
                vendasProdutosDAO.delete(gldVendasRoupasProdutos);
            }
              vendasDAO.delete(viewBean()); 
        }
      
       Util.limpar(jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto);
       controllerVendasProd.setList(new ArrayList());
    }//GEN-LAST:event_jBtnGldExcluirActionPerformed

    private void jBtnGldConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldConfirmarActionPerformed
        VendasDAO vendasDAO = new VendasDAO();
        VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
        GldVendasRoupas gldVendasRoupas = viewBean();
        if (incluir == true) {
            vendasDAO.insert(gldVendasRoupas);
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                GldVendasRoupasProdutos gldVendasRoupasProdutos = controllerVendasProd.getBean(ind);
                gldVendasRoupasProdutos.setGldVendasRoupas(gldVendasRoupas);
                vendasProdutosDAO.insert(gldVendasRoupasProdutos);
            }
        } else {
            vendasDAO.update(gldVendasRoupas);

        }
         
         Util.habilitar(false, jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto,
            jTxtGldFormaPagamento, jCboGldClientes, jCboGldUsuarios, 
            jBtnGldConfirmar, jBtnGldCancelar,jBtnGldIncluirProd, jBtnGldAlterarProd, jBtnGldExcluirProd);
        Util.habilitar(true, jBtnGldIncluir, jBtnGldAlterar, jBtnGldExcluir, jBtnGldPesquisar);
        Util.limpar(jTxtGldCodigo, jFmtGldDataVenda, jTxtGldTotal, jTxtGldDesconto);
    }//GEN-LAST:event_jBtnGldConfirmarActionPerformed

    private void jBtnGldExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldExcluirProdActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            Util.mensagem("È necessário selecionar uma linha para excluir.");
        } else {
            if (Util.pergunta("Deseja excluir o produto ?") == true) {
                controllerVendasProd.removeBean(jTable1.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jBtnGldExcluirProdActionPerformed

    private void jBtnGldAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldAlterarProdActionPerformed
        // TODO add your handling code here:
        JDlgVendasProdutos jDlgVendasProdutos = new JDlgVendasProdutos(null, true);
        jDlgVendasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnGldAlterarProdActionPerformed

    private void jBtnGldIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGldIncluirProdActionPerformed
        // TODO add your handling code here:
        JDlgVendasProdutos jDlgVendasProdutos = new JDlgVendasProdutos(null, true);
        jDlgVendasProdutos.setTelaAnterior(this);
        jDlgVendasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnGldIncluirProdActionPerformed

    private void jCboGldUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboGldUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboGldUsuariosActionPerformed

    private void jTxtGldFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGldFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtGldFormaPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas dialog = new JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGldAlterar;
    private javax.swing.JButton jBtnGldAlterarProd;
    private javax.swing.JButton jBtnGldCancelar;
    private javax.swing.JButton jBtnGldConfirmar;
    private javax.swing.JButton jBtnGldExcluir;
    private javax.swing.JButton jBtnGldExcluirProd;
    private javax.swing.JButton jBtnGldIncluir;
    private javax.swing.JButton jBtnGldIncluirProd;
    private javax.swing.JButton jBtnGldPesquisar;
    private javax.swing.JComboBox<GldClientes> jCboGldClientes;
    private javax.swing.JComboBox<GldUsuarios> jCboGldUsuarios;
    private javax.swing.JFormattedTextField jFmtGldDataVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtGldCodigo;
    private javax.swing.JTextField jTxtGldDesconto;
    private javax.swing.JTextField jTxtGldFormaPagamento;
    private javax.swing.JTextField jTxtGldTotal;
    // End of variables declaration//GEN-END:variables
}
