    package bean;
// Generated 09/10/2025 22:31:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GldClientes generated by hbm2java
 */
@Entity
@Table(name="gld_clientes"
    ,catalog="sistemadolacio"
)
public class GldClientes  implements java.io.Serializable {


     private int gldIdClientes;
     private String gldNome;
     private String gldCpf;
     private String gldEmail;
     private String gldTelefone;
     private String gldRua;
     private String gldBairro;
     private String gldNumeroCasa;
     private String gldCidade;
     private String gldEstado;
     private String gldCep;
     private int gldIdade;
     private String gldTelefoneresidencial;
     private Date gldDataNascimento;
     private String gldSexo;
   

    public GldClientes() {
    }

	
    public GldClientes(int gldIdClientes, String gldNome, String gldCpf, String gldEmail, String gldTelefone, String gldRua, String gldBairro, String gldNumeroCasa, String gldCidade, String gldEstado, String gldCep, int gldIdade, String gldTelefoneresidencial, String gldSexo) {
        this.gldIdClientes = gldIdClientes;
        this.gldNome = gldNome;
        this.gldCpf = gldCpf;
        this.gldEmail = gldEmail;
        this.gldTelefone = gldTelefone;
        this.gldRua = gldRua;
        this.gldBairro = gldBairro;
        this.gldNumeroCasa = gldNumeroCasa;
        this.gldCidade = gldCidade;
        this.gldEstado = gldEstado;
        this.gldCep = gldCep;
        this.gldIdade = gldIdade;
        this.gldTelefoneresidencial = gldTelefoneresidencial;
        this.gldSexo = gldSexo;
    }
    public GldClientes(int gldIdClientes, String gldNome, String gldCpf, String gldEmail, String gldTelefone, String gldRua, String gldBairro, String gldNumeroCasa, String gldCidade, String gldEstado, String gldCep, int gldIdade, String gldTelefoneresidencial, Date gldDataNascimento, String gldSexo, Set gldVendasRoupases) {
       this.gldIdClientes = gldIdClientes;
       this.gldNome = gldNome;
       this.gldCpf = gldCpf;
       this.gldEmail = gldEmail;
       this.gldTelefone = gldTelefone;
       this.gldRua = gldRua;
       this.gldBairro = gldBairro;
       this.gldNumeroCasa = gldNumeroCasa;
       this.gldCidade = gldCidade;
       this.gldEstado = gldEstado;
       this.gldCep = gldCep;
       this.gldIdade = gldIdade;
       this.gldTelefoneresidencial = gldTelefoneresidencial;
       this.gldDataNascimento = gldDataNascimento;
       this.gldSexo = gldSexo;
       
    }
   
     @Id 

    
    @Column(name="gld_idClientes", unique=true, nullable=false)
    public int getGldIdClientes() {
        return this.gldIdClientes;
    }
    
    public void setGldIdClientes(int gldIdClientes) {
        this.gldIdClientes = gldIdClientes;
    }

    
    @Column(name="gld_nome", nullable=false, length=50)
    public String getGldNome() {
        return this.gldNome;
    }
    
    public void setGldNome(String gldNome) {
        this.gldNome = gldNome;
    }

    
    @Column(name="gld_cpf", nullable=false, length=14)
    public String getGldCpf() {
        return this.gldCpf;
    }
    
    public void setGldCpf(String gldCpf) {
        this.gldCpf = gldCpf;
    }

    
    @Column(name="gld_email", nullable=false, length=80)
    public String getGldEmail() {
        return this.gldEmail;
    }
    
    public void setGldEmail(String gldEmail) {
        this.gldEmail = gldEmail;
    }

    
    @Column(name="gld_telefone", nullable=false, length=15)
    public String getGldTelefone() {
        return this.gldTelefone;
    }
    
    public void setGldTelefone(String gldTelefone) {
        this.gldTelefone = gldTelefone;
    }

    
    @Column(name="gld_rua", nullable=false, length=50)
    public String getGldRua() {
        return this.gldRua;
    }
    
    public void setGldRua(String gldRua) {
        this.gldRua = gldRua;
    }

    
    @Column(name="gld_bairro", nullable=false, length=100)
    public String getGldBairro() {
        return this.gldBairro;
    }
    
    public void setGldBairro(String gldBairro) {
        this.gldBairro = gldBairro;
    }

    
    @Column(name="gld_numero_casa", nullable=false, length=3)
    public String getGldNumeroCasa() {
        return this.gldNumeroCasa;
    }
    
    public void setGldNumeroCasa(String gldNumeroCasa) {
        this.gldNumeroCasa = gldNumeroCasa;
    }

    
    @Column(name="gld_cidade", nullable=false, length=100)
    public String getGldCidade() {
        return this.gldCidade;
    }
    
    public void setGldCidade(String gldCidade) {
        this.gldCidade = gldCidade;
    }

    
    @Column(name="gld_estado", nullable=false, length=50)
    public String getGldEstado() {
        return this.gldEstado;
    }
    
    public void setGldEstado(String gldEstado) {
        this.gldEstado = gldEstado;
    }

    
    @Column(name="gld_cep", nullable=false, length=10)
    public String getGldCep() {
        return this.gldCep;
    }
    
    public void setGldCep(String gldCep) {
        this.gldCep = gldCep;
    }

    
    @Column(name="gld_idade", nullable=false)
    public int getGldIdade() {
        return this.gldIdade;
    }
    
    public void setGldIdade(int gldIdade) {
        this.gldIdade = gldIdade;
    }

    
    @Column(name="gld_Telefoneresidencial", nullable=false, length=10)
    public String getGldTelefoneresidencial() {
        return this.gldTelefoneresidencial;
    }
    
    public void setGldTelefoneresidencial(String gldTelefoneresidencial) {
        this.gldTelefoneresidencial = gldTelefoneresidencial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gld_data_nascimento", length=10)
    public Date getGldDataNascimento() {
        return this.gldDataNascimento;
    }
    
    public void setGldDataNascimento(Date gldDataNascimento) {
        this.gldDataNascimento = gldDataNascimento;
    }

    
    @Column(name="gld_sexo", nullable=false, length=1)
    public String getGldSexo() {
        return this.gldSexo;
    }
    
    public void setGldSexo(String gldSexo) {
        this.gldSexo = gldSexo;
    }
    
    @Override
    public String toString() {
    return this.getGldNome(); 
}
    @Override
public boolean equals(Object obj) {
    if (obj instanceof GldClientes) {
        GldClientes clientes = (GldClientes) obj;
        return this.getGldIdClientes()== clientes.getGldIdClientes();
    }
    return false;
}

   
}






