package bean;
// Generated 09/10/2025 22:31:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GldFuncionarios generated by hbm2java
 */
@Entity
@Table(name="gld_funcionarios"
    ,catalog="sistemadolacio"
)
public class GldFuncionarios  implements java.io.Serializable {


     private int gldIdFuncionario;
     private String gldNome;
     private String gldCpf;
     private Date gldDataNascimento;
     private String gldEmail;
     private String gldTelefone;
     private String gldFuncao;
     private double gldSalario;
     private String gldAtivo;

    public GldFuncionarios() {
    }

	
    public GldFuncionarios(int gldIdFuncionario, String gldNome, String gldCpf, String gldEmail, String gldTelefone, String gldFuncao, double gldSalario, String gldAtivo) {
        this.gldIdFuncionario = gldIdFuncionario;
        this.gldNome = gldNome;
        this.gldCpf = gldCpf;
        this.gldEmail = gldEmail;
        this.gldTelefone = gldTelefone;
        this.gldFuncao = gldFuncao;
        this.gldSalario = gldSalario;
        this.gldAtivo = gldAtivo;
    }
    public GldFuncionarios(int gldIdFuncionario, String gldNome, String gldCpf, Date gldDataNascimento, String gldEmail, String gldTelefone, String gldFuncao, double gldSalario, String gldAtivo) {
       this.gldIdFuncionario = gldIdFuncionario;
       this.gldNome = gldNome;
       this.gldCpf = gldCpf;
       this.gldDataNascimento = gldDataNascimento;
       this.gldEmail = gldEmail;
       this.gldTelefone = gldTelefone;
       this.gldFuncao = gldFuncao;
       this.gldSalario = gldSalario;
       this.gldAtivo = gldAtivo;
    }
   
     @Id 

    
    @Column(name="gld_idFuncionario", unique=true, nullable=false)
    public int getGldIdFuncionario() {
        return this.gldIdFuncionario;
    }
    
    public void setGldIdFuncionario(int gldIdFuncionario) {
        this.gldIdFuncionario = gldIdFuncionario;
    }

    
    @Column(name="gld_nome", nullable=false, length=50)
    public String getGldNome() {
        return this.gldNome;
    }
    
    public void setGldNome(String gldNome) {
        this.gldNome = gldNome;
    }

    
    @Column(name="gld_cpf", nullable=false, length=14)
    public String getGldCpf() {
        return this.gldCpf;
    }
    
    public void setGldCpf(String gldCpf) {
        this.gldCpf = gldCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gld_dataNascimento", length=10)
    public Date getGldDataNascimento() {
        return this.gldDataNascimento;
    }
    
    public void setGldDataNascimento(Date gldDataNascimento) {
        this.gldDataNascimento = gldDataNascimento;
    }

    
    @Column(name="gld_email", nullable=false, length=80)
    public String getGldEmail() {
        return this.gldEmail;
    }
    
    public void setGldEmail(String gldEmail) {
        this.gldEmail = gldEmail;
    }

    
    @Column(name="gld_telefone", nullable=false, length=15)
    public String getGldTelefone() {
        return this.gldTelefone;
    }
    
    public void setGldTelefone(String gldTelefone) {
        this.gldTelefone = gldTelefone;
    }

    
    @Column(name="gld_funcao", nullable=false, length=50)
    public String getGldFuncao() {
        return this.gldFuncao;
    }
    
    public void setGldFuncao(String gldFuncao) {
        this.gldFuncao = gldFuncao;
    }

    
    @Column(name="gld_salario", nullable=false, precision=10)
    public double getGldSalario() {
        return this.gldSalario;
    }
    
    public void setGldSalario(double gldSalario) {
        this.gldSalario = gldSalario;
    }

    
    @Column(name="gld_ativo", nullable=false, length=1)
    public String getGldAtivo() {
        return this.gldAtivo;
    }
    
    public void setGldAtivo(String gldAtivo) {
        this.gldAtivo = gldAtivo;
    }




}


