package bean;
// Generated 09/10/2025 22:31:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GldProdutosRoupas generated by hbm2java
 */
@Entity
@Table(name="gld_produtos_roupas"
    ,catalog="sistemadolacio"
)
public class GldProdutosRoupas  implements java.io.Serializable {


     private int gldIdProdutos;
     private String gldNome;
     private String gldCategoria;
     private String gldTamanho;
     private String gldCor;
     private double gldPreco;
     private String gldDescricao;


    public GldProdutosRoupas() {
    }

	
    public GldProdutosRoupas(int gldIdProdutos, String gldNome, String gldCategoria, String gldTamanho, String gldCor, double gldPreco, String gldDescricao) {
        this.gldIdProdutos = gldIdProdutos;
        this.gldNome = gldNome;
        this.gldCategoria = gldCategoria;
        this.gldTamanho = gldTamanho;
        this.gldCor = gldCor;
        this.gldPreco = gldPreco;
        this.gldDescricao = gldDescricao;
    }
    public GldProdutosRoupas(int gldIdProdutos, String gldNome, String gldCategoria, String gldTamanho, String gldCor, double gldPreco, String gldDescricao, Set gldVendasRoupasProdutoses) {
       this.gldIdProdutos = gldIdProdutos;
       this.gldNome = gldNome;
       this.gldCategoria = gldCategoria;
       this.gldTamanho = gldTamanho;
       this.gldCor = gldCor;
       this.gldPreco = gldPreco;
       this.gldDescricao = gldDescricao;
       
    }
   
     @Id 

    
    @Column(name="gld_idProdutos", unique=true, nullable=false)
    public int getGldIdProdutos() {
        return this.gldIdProdutos;
    }
    
    public void setGldIdProdutos(int gldIdProdutos) {
        this.gldIdProdutos = gldIdProdutos;
    }

    
    @Column(name="gld_nome", nullable=false, length=100)
    public String getGldNome() {
        return this.gldNome;
    }
    
    public void setGldNome(String gldNome) {
        this.gldNome = gldNome;
    }

    
    @Column(name="gld_categoria", nullable=false, length=50)
    public String getGldCategoria() {
        return this.gldCategoria;
    }
    
    public void setGldCategoria(String gldCategoria) {
        this.gldCategoria = gldCategoria;
    }

    
    @Column(name="gld_tamanho", nullable=false, length=2)
    public String getGldTamanho() {
        return this.gldTamanho;
    }
    
    public void setGldTamanho(String gldTamanho) {
        this.gldTamanho = gldTamanho;
    }

    
    @Column(name="gld_cor", nullable=false, length=50)
    public String getGldCor() {
        return this.gldCor;
    }
    
    public void setGldCor(String gldCor) {
        this.gldCor = gldCor;
    }

    
    @Column(name="gld_preco", nullable=false, precision=10)
    public double getGldPreco() {
        return this.gldPreco;
    }
    
    public void setGldPreco(double gldPreco) {
        this.gldPreco = gldPreco;
    }

    
    @Column(name="gld_descricao", nullable=false, length=65535)
    public String getGldDescricao() {
        return this.gldDescricao;
    }
    
    public void setGldDescricao(String gldDescricao) {
        this.gldDescricao = gldDescricao;
    }





}


