package bean;
// Generated 09/10/2025 22:31:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GldUsuarios generated by hbm2java
 */
@Entity
@Table(name="gld_usuarios"
    ,catalog="sistemadolacio"
)
public class GldUsuarios  implements java.io.Serializable {


     private int gldIdUsuarios;
     private String gldNome;
     private String gldApelido;
     private String gldCpf;
     private Date gldDataNascimento;
     private String gldSenha;
     private int gldNivel;
     private String gldAtivo;


    public GldUsuarios() {
    }

	
    public GldUsuarios(int gldIdUsuarios, String gldNome, String gldApelido, String gldSenha, int gldNivel, String gldAtivo) {
        this.gldIdUsuarios = gldIdUsuarios;
        this.gldNome = gldNome;
        this.gldApelido = gldApelido;
        this.gldSenha = gldSenha;
        this.gldNivel = gldNivel;
        this.gldAtivo = gldAtivo;
    }
    public GldUsuarios(int gldIdUsuarios, String gldNome, String gldApelido, String gldCpf, Date gldDataNascimento, String gldSenha, int gldNivel, String gldAtivo, Set gldVendasRoupases) {
       this.gldIdUsuarios = gldIdUsuarios;
       this.gldNome = gldNome;
       this.gldApelido = gldApelido;
       this.gldCpf = gldCpf;
       this.gldDataNascimento = gldDataNascimento;
       this.gldSenha = gldSenha;
       this.gldNivel = gldNivel;
       this.gldAtivo = gldAtivo;
      
    }
   
     @Id 

    
    @Column(name="gld_idUsuarios", unique=true, nullable=false)
    public int getGldIdUsuarios() {
        return this.gldIdUsuarios;
    }
    
    public void setGldIdUsuarios(int gldIdUsuarios) {
        this.gldIdUsuarios = gldIdUsuarios;
    }

    
    @Column(name="gld_nome", nullable=false, length=50)
    public String getGldNome() {
        return this.gldNome;
    }
    
    public void setGldNome(String gldNome) {
        this.gldNome = gldNome;
    }

    
    @Column(name="gld_apelido", nullable=false, length=25)
    public String getGldApelido() {
        return this.gldApelido;
    }
    
    public void setGldApelido(String gldApelido) {
        this.gldApelido = gldApelido;
    }

    
    @Column(name="gld_cpf", length=14)
    public String getGldCpf() {
        return this.gldCpf;
    }
    
    public void setGldCpf(String gldCpf) {
        this.gldCpf = gldCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gld_dataNascimento", length=10)
    public Date getGldDataNascimento() {
        return this.gldDataNascimento;
    }
    
    public void setGldDataNascimento(Date gldDataNascimento) {
        this.gldDataNascimento = gldDataNascimento;
    }

    
    @Column(name="gld_senha", nullable=false, length=20)
    public String getGldSenha() {
        return this.gldSenha;
    }
    
    public void setGldSenha(String gldSenha) {
        this.gldSenha = gldSenha;
    }

    
    @Column(name="gld_nivel", nullable=false)
    public int getGldNivel() {
        return this.gldNivel;
    }
    
    public void setGldNivel(int gldNivel) {
        this.gldNivel = gldNivel;
    }

    
    @Column(name="gld_ativo", nullable=false, length=1)
    public String getGldAtivo() {
        return this.gldAtivo;
    }
    
    public void setGldAtivo(String gldAtivo) {
        this.gldAtivo = gldAtivo;
    }





}


