package bean;
// Generated 09/10/2025 22:31:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GldVendasRoupas generated by hbm2java
 */
@Entity
@Table(name="gld_vendas_roupas"
    ,catalog="sistemadolacio"
)
public class GldVendasRoupas  implements java.io.Serializable {


     private int gldIdVendas;
     private GldClientes gldClientes;
     private GldUsuarios gldUsuarios;
     private Date gldDataVenda;
     private double gldTotal;
     private int gldFormaPagamento;
     private double gldDesconto;
    

    public GldVendasRoupas() {
    }

	
    public GldVendasRoupas(int gldIdVendas, Date gldDataVenda, double gldTotal, int gldFormaPagamento, double gldDesconto) {
        this.gldIdVendas = gldIdVendas;
        this.gldDataVenda = gldDataVenda;
        this.gldTotal = gldTotal;
        this.gldFormaPagamento = gldFormaPagamento;
        this.gldDesconto = gldDesconto;
    }
    public GldVendasRoupas(int gldIdVendas, GldClientes gldClientes, GldUsuarios gldUsuarios, Date gldDataVenda, double gldTotal, int gldFormaPagamento, double gldDesconto, Set gldVendasRoupasProdutoses) {
       this.gldIdVendas = gldIdVendas;
       this.gldClientes = gldClientes;
       this.gldUsuarios = gldUsuarios;
       this.gldDataVenda = gldDataVenda;
       this.gldTotal = gldTotal;
       this.gldFormaPagamento = gldFormaPagamento;
       this.gldDesconto = gldDesconto;
       
    }
   
     @Id 

    
    @Column(name="gld_idVendas", unique=true, nullable=false)
    public int getGldIdVendas() {
        return this.gldIdVendas;
    }
    
    public void setGldIdVendas(int gldIdVendas) {
        this.gldIdVendas = gldIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gld_cliente")
    public GldClientes getGldClientes() {
        return this.gldClientes;
    }
    
    public void setGldClientes(GldClientes gldClientes) {
        this.gldClientes = gldClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gld_usuario")
    public GldUsuarios getGldUsuarios() {
        return this.gldUsuarios;
    }
    
    public void setGldUsuarios(GldUsuarios gldUsuarios) {
        this.gldUsuarios = gldUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gld_dataVenda", nullable=false, length=10)
    public Date getGldDataVenda() {
        return this.gldDataVenda;
    }
    
    public void setGldDataVenda(Date gldDataVenda) {
        this.gldDataVenda = gldDataVenda;
    }

    
    @Column(name="gld_total", nullable=false, precision=10)
    public double getGldTotal() {
        return this.gldTotal;
    }
    
    public void setGldTotal(double gldTotal) {
        this.gldTotal = gldTotal;
    }

    
    @Column(name="gld_forma_pagamento", nullable=false, length=50)
    public int getGldFormaPagamento() {
        return this.gldFormaPagamento;
    }
    
    public void setGldFormaPagamento(int gldFormaPagamento) {
        this.gldFormaPagamento = gldFormaPagamento;
    }

    
    @Column(name="gld_desconto", nullable=false, precision=10)
    public double getGldDesconto() {
        return this.gldDesconto;
    }
    
    public void setGldDesconto(double gldDesconto) {
        this.gldDesconto = gldDesconto;
    }






}


