package bean;
// Generated 09/10/2025 22:31:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GldVendasRoupasProdutos generated by hbm2java
 */
@Entity
@Table(name="gld_vendas_roupas_produtos"
    ,catalog="sistemadolacio"
)
public class GldVendasRoupasProdutos  implements java.io.Serializable {


     private Integer gldIdVendasProdutos;
     private GldProdutosRoupas gldProdutosRoupas;
     private GldVendasRoupas gldVendasRoupas;
     private int gldQuantidade;
     private double gldValorUnitario;
     private String gldStatusProduto;

    public GldVendasRoupasProdutos() {
    }

    public GldVendasRoupasProdutos(GldProdutosRoupas gldProdutosRoupas, GldVendasRoupas gldVendasRoupas, int gldQuantidade, double gldValorUnitario, String gldStatusProduto) {
       this.gldProdutosRoupas = gldProdutosRoupas;
       this.gldVendasRoupas = gldVendasRoupas;
       this.gldQuantidade = gldQuantidade;
       this.gldValorUnitario = gldValorUnitario;
       this.gldStatusProduto = gldStatusProduto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="gld_idVendasProdutos", unique=true, nullable=false)
    public Integer getGldIdVendasProdutos() {
        return this.gldIdVendasProdutos;
    }
    
    public void setGldIdVendasProdutos(Integer gldIdVendasProdutos) {
        this.gldIdVendasProdutos = gldIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gld_produto", nullable=false)
    public GldProdutosRoupas getGldProdutosRoupas() {
        return this.gldProdutosRoupas;
    }
    
    public void setGldProdutosRoupas(GldProdutosRoupas gldProdutosRoupas) {
        this.gldProdutosRoupas = gldProdutosRoupas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gld_venda", nullable=false)
    public GldVendasRoupas getGldVendasRoupas() {
        return this.gldVendasRoupas;
    }
    
    public void setGldVendasRoupas(GldVendasRoupas gldVendasRoupas) {
        this.gldVendasRoupas = gldVendasRoupas;
    }

    
    @Column(name="gld_quantidade", nullable=false)
    public int getGldQuantidade() {
        return this.gldQuantidade;
    }
    
    public void setGldQuantidade(int gldQuantidade) {
        this.gldQuantidade = gldQuantidade;
    }

    
    @Column(name="gld_valor_unitario", nullable=false, precision=10)
    public double getGldValorUnitario() {
        return this.gldValorUnitario;
    }
    
    public void setGldValorUnitario(double gldValorUnitario) {
        this.gldValorUnitario = gldValorUnitario;
    }

    
    @Column(name="gld_status_produto", nullable=false, length=20)
    public String getGldStatusProduto() {
        return this.gldStatusProduto;
    }
    
    public void setGldStatusProduto(String gldStatusProduto) {
        this.gldStatusProduto = gldStatusProduto;
    }




}


